[tool.bumpversion]
current_version = "0.10.0"
commit = true
tag = true
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = 'CHANGES.rst'
search = "YYYY-MM-DD"
replace = "{now:%Y-%m-%d}"

[[tool.bumpversion.files]]
filename = "setup.py"
